const descriptors = [
  'Everything but the',
  '5 Cheese',
  'Dark Chocolate',
  'Asian Inspired',
  'Crispy, Crunchy',
  'Gluten Free',
  'Unexpected',
  "A Midsummer Night's",
  'Chili Spiced',
  'Pumpkin Spiced',
  'Triple Ginger',
  'Candy Cane',
  'Toasted',
  'Honey Butter',
  'Sweet Potato',
  'Chocolate Covered',
  'Cinnamon Dusted',
  'French Inspired',
  'French',
  'Mexican',
  'Mexican Inspired',
  'Vegan',
  'Grilled',
  'Sea-Salt',
  'Honey Sriracha',
  'Thinly Sliced',
  'Whipped',
  'Sweet & Sour',
  'Sweet & Spicy',
  'Keto',
  'Pickled',
  'Fermented',
  'Tumeric Ginger',
  'Buttered'
]
const ingredients = [
  'Masala',
  'Mochi',
  'Cheddar Cheese',
  'Almond Butter',
  'Balsamic',
  'Edamame',
  'Buffalo',
  'Whole Grain',
  'Brussel Sprout',
  'Peruvian',
  'Key Lime',
  'Kale',
  'Coconut Oil',
  'Cookie Butter',
  'Basmati Rice',
  'Corned Beef',
  'Caramel Filled',
  'Powerberry',
  'Bagel',
  'Persian Cucumber',
  'Cold Brew',
  'Paneer',
  'Turkey & Gravy',
  'Riced Cauliflower',
  'Joe-Joe',
  "Cold Pressed",
  'Maple',
  'Mexican Style',
  'Mac & Cheese',
  'Mandarin Orange',
  'Superfood',
  'Corn',
  'Elote',
  'Brioche',
  'Teriyaki',
  'Tapenade',
  'Apple Cider',
  'Cinnamon Sugar',
  'Kimchi',
  'Peppermint'
]
const products = [
  'Nuggets',
  'Kale Slaw',
  'Baking Mix',
  'Burgers',
  'Gyoza',
  'Yogurt',
  'Granola',
  'Spread',
  'Bites',
  'Kombucha',
  'Simmer Sauce',
  'Seasoning Blend',
  'Body Butter',
  'Dog Treats',
  'Tuscan Pane',
  'Vodka',
  'Winter Ale',
  'Stir Fry',
  'Coffee',
  'Dried Fruit Blend',
  'Pizza Crust',
  'Juice',
  'Salsa',
  'Maple Ladders',
  'Gelato',
  'Pasta Sauce',
  'Tea Concentrate',
  'Sparkling Water',
  'Muffins',
  'Cake Mix',
  'Cookie Mix',
  'Smoothie Blend',
  'Taco Product',
  'Gnocchi',
  'Gummies',
  'Dunkers',
  'Laundry Detergent',
  'Cat Treats',
  'Nut Butter',
  'Macaroons',
  'Slices',
  'Vinagrette',
  'Mustard',
  'Dumplings',
  'Bao Buns',
  'Pancakes',
  'Desert Bars',
  'Kettle Chips',
]

export function handler(event, context, callback) {
  const descriptor = descriptors[Math.floor(Math.random() * (descriptors.length))];
  const ingredient = ingredients[Math.floor(Math.random() * (ingredients.length))];
  const product = products[Math.floor(Math.random() * (products.length))];

  callback(null, {
    statusCode: 200,
    body: JSON.stringify({ msg: descriptor + ' ' + ingredient + ' ' + product }),
  })
}
